version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql_80
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
